### PR TITLE
Allow per-frame delay configuration in StreamingGifWriter

### PR DESCRIPTION
**Pull request by stanch**
This is really helpful when you have key frames that should be shown longer. Not having to write the same frame several times with the default delay gives a significant performance speedup.

### CODE REVIEW

**Comment by sksamuel** [comment]
awesome

**Comment by stanch** [comment]
Thanks for the quick merge! This did not make it into `3.0.0-alpha2`, right? Do you mind doing a release with this commit?

**Comment by sksamuel** [comment]
Yes I can do. I can't promise API won't change between alpha2/3 and final of 3.

**Comment by stanch** [comment]
That would be great. No problem, I am happy to adapt :)

**Comment by sksamuel** [comment]
alpha3 will be in central in 30.

**Pull request merged**
