### PR TITLE
fix color average

### LINKED ISSUE #279: average implementation is not correct
https://github.com/sksamuel/scrimage/blob/a5bd523e1beac9f25721fee9410e900c5bfe5eef/scrimage-core/src/main/java/com/sksamuel/scrimage/color/Color.java#L68-L82

```
rOut = (rA * aA / 255) + (rB * aB * (255 - aA) / (255*255))
gOut = (gA * aA / 255) + (gB * aB * (255 - aA) / (255*255))
bOut = (bA * aA / 255) + (bB * aB * (255 - aA) / (255*255))
aOut = aA + (aB * (255 - aA) / 255)
```

### PR DESCRIPTION
**Pull request by tonny008**
fixes #279 

```
rOut = (rA * aA / 255) + (rB * aB * (255 - aA) / (255*255))
gOut = (gA * aA / 255) + (gB * aB * (255 - aA) / (255*255))
bOut = (bA * aA / 255) + (bB * aB * (255 - aA) / (255*255))
aOut = aA + (aB * (255 - aA) / 255)
```

### CODE REVIEW

**Comment by sksamuel** [comment]
Awesome thank you !

**Comment by sksamuel** [comment]
Looks like a test failure.

**Comment by tonny008** [comment]
```
com.sksamuel.scrimage.core.ScalingDeadlockTest > image scale should not deadlock on multiple concurrent scales FAILED
    io.kotest.assertions.AssertionFailedError: expected:<50> but was:<49>
        at app//com.sksamuel.scrimage.core.ScalingDeadlockTest$1$1.invokeSuspend(ScalingDeadlockTest.kt:30)
        at app//com.sksamuel.scrimage.core.ScalingDeadlockTest$1$1.invoke(ScalingDeadlockTest.kt)
        at app//com.sksamuel.scrimage.core.ScalingDeadlockTest$1$1.invoke(ScalingDeadlockTest.kt)
```
`val images = mutableListOf<ImmutableImage>()` is it thread safe?

**Comment by sksamuel** [comment]
Ah yeah I guess not.

**Pull request merged**
