### PR TITLE
Calculation x and y for cover based on given Position

### PR DESCRIPTION
**Pull request by ptrlaszlo**
Fix for issue https://github.com/sksamuel/scrimage/issues/102

### CODE REVIEW

**Comment by sksamuel** [comment]
:+1:

**Comment by ptrlaszlo** [comment]
@sksamuel when do you plan to release the next version?

**Comment by sksamuel** [comment]
Will do it today.

**Comment by ptrlaszlo** [comment]
Thanks!

**Comment by sksamuel** [comment]
2.1.5 is released

**Pull request merged**
